### PR TITLE
fix overflow with correlation coefficient ..

### PR DESCRIPTION
**Pull request by hayguen**
see commits documentation

### CODE REVIEW

**Comment by dbry** [comment]
Hi, and thanks for all the work you've done here, and for the previous patches!

I like most of this, but I don't think going to a 64-bit integer is the best way to address the overflow issue. I've worked out what I think is a better scheme and I'll be pushing some changes that we can discuss, in addition to some other improvements that I've made that I haven't committed. I'll also incorporate some of your other changes.

Thanks again!

**Comment by hayguen** [comment]
that's fine. we'll discuss after your commit / branch.
let me amend, that gcc UBsan (undefined behaviour sanitizer) catched that overflow ..
and then, i verified, that it's happening with real world data inserting asserts.

by the way, i realized, that you mainly (always?) use pure C - not even an old c++ standard.
would you be so kind to explain why you're restricting yourself to C?
a private message to my email is fine: h_ayguen@web.de

**Comment by hayguen** [comment]
rethinking, how to avoid the 64 bit:
the sum over up to max period lengths requires up to 16 + 10 = 26 bits.
same for diff.
with min period length = 24, the sum could get right shifted by 4 (divided by 16) without real loss of precision, right? then we'd yield 22 bits. enough for the additional left shift by 7 (* 128) for the precision for the following division.
merging both operations, a left shift by 3 bits is sufficient and should be good enough .. and yield 29 bits.
that's still safe for the limit of 30 (uint32_max /4) bits :-)

i had noticed but forgotten following corner case:
having all input = 0 over min_period, diff but also sum would get 0 .. now resulting in corr_max, which can't get beaten if non-zero data would start with higher periods! thus, one more if or ?-operator should be spent for the rare case of diff == 0.

**Comment by hayguen** [comment]
the initial reason for this pull request, the overflow, is solved better with https://github.com/dbry/audio-stretch/pull/4

i'll make a separate "cosmetic" pull request, for the explicit sized types and const stuff ..

**Comment by dbry** [comment]
Thanks! Please hold off on the "cosmetic" PR for now. Once I have my changes in I'll make a pass at it using your previous PR as a guide. To be honest, I'm not a big fan of some of these as I find they sometimes obfuscate more than elucidate (which is also why I'm not a big fan of a lot of C++ code I have to deal with), so I'll cherry-pick the ones I like.

**Pull request closed without merging**
